#!/usr/bin/env python3
# auto_wire_void_beast.py
# Safely injects a tiny void-beast cycle hook into voidx2_0.py.
# Creates a backup and does a syntax check. Reversible.
import re, sys, shutil, time
from pathlib import Path
import py_compile

ROOT = Path.cwd()
SRC = ROOT / "voidx2_0.py"

if not SRC.exists():
    print("Error: voidx2_0.py not found in", ROOT)
    sys.exit(1)

backup = ROOT / f"voidx2_0_autowire_backup_{int(time.time())}.py"
shutil.copy2(SRC, backup)
print("Backup created:", backup.name)

orig = SRC.read_text(encoding="utf-8")
lines = orig.splitlines(keepends=True)

# --- create safe injection import block (will not break __future__, docstring, shebang) ---
integration_block = r'''
# ==== VOID BEAST AUTO-WIRE IMPORTS ====
# auto-generated by auto_wire_void_beast.py
try:
    import beast_helpers as vb_helpers
    import beast_threshold as vb_threshold
    import beast_risk as vb_risk
    import beast_protection as vb_protect
    import beast_dashboard as vb_dashboard
    import beast_sentiment as vb_sent
    import beast_scoring as vb_scoring
    import beast_calendar as vb_calendar
    import beast_symbols as vb_symbols
    import beast_liquidity as vb_liq
except Exception as _vb_e:
    import logging
    logging.getLogger("void_beast").warning("void_beast auto-wire import failure: %s", _vb_e)
# ==== END VOID BEAST AUTO-WIRE IMPORTS ====
'''

# --- small cycle hook function to be injected once (defensive, minimal) ---
hook_function = r'''
# ==== VOID BEAST AUTO CYCLE HOOK ====
def __void_beast_cycle():
    """
    Lightweight, defensive hook called once per main loop cycle.
    It runs a small set of beast module calls and publishes a snapshot to beast_dashboard.
    Never raises exceptions (internal exceptions are caught and logged).
    """
    try:
        # safe imports (may be missing in some setups)
        try:
            from beast_threshold import get_current_threshold, apply_gravity_and_volatility
            from beast_sentiment import SentimentEngine
            from beast_risk import compute_dynamic_risk
            from beast_dashboard import publish_cycle
            from beast_protection import sqf_check
        except Exception as _e:
            # if modules missing, quietly return
            import logging
            logging.getLogger("void_beast").debug("void_beast hook: modules missing: %s", _e)
            return

        # get current threshold (safe)
        try:
            current_t = get_current_threshold()
        except Exception:
            current_t = 0.18

        # sentiment: if the main bot provides a cached 'BEAST_NEWS_CACHE' variable in globals() we use it
        articles = None
        try:
            g = globals()
            articles = g.get("BEAST_NEWS_CACHE") or g.get("news_cache") or None
        except Exception:
            articles = None

        sent_engine = getattr(__void_beast_cycle, "_sent_engine", None)
        if sent_engine is None:
            sent_engine = SentimentEngine(alpha=0.2, window=5)
            setattr(__void_beast_cycle, "_sent_engine", sent_engine)

        try:
            smoothed_sent = sent_engine.score_from_headlines(articles or [])
        except Exception:
            smoothed_sent = 0.0

        # compute a dynamic risk (best-effort)
        try:
            # best-effort: read tech/model/fund if main bot exposed them in globals()
            tech = globals().get("LAST_TECH_SCORE", 0.0)
            model = globals().get("LAST_MODEL_SCORE", 0.0)
            fund = globals().get("LAST_FUND_SCORE", 0.0)
            risk_val, risk_mode = compute_dynamic_risk(tech, fund, smoothed_sent)
        except Exception:
            risk_val, risk_mode = 0.003, "default"

        # apply small gravity update (volatility_adj unknown here; use 0)
        try:
            new_t = apply_gravity_and_volatility(current_t, volatility_adj=0.0)
        except Exception:
            new_t = current_t

        # quick SQF check (best-effort)
        try:
            # attempt to read some safe values from globals or fallback constants
            spread_points = globals().get("CURRENT_SPREAD_POINTS", None)
            atr_now = globals().get("CURRENT_ATR", None)
            atr_avg = globals().get("ATR_AVG", None)
            recent_move_pct = globals().get("RECENT_MOVE_PCT", None)
            ok, reason = sqf_check("GENERIC", spread_points, atr_now, atr_avg, recent_move_pct)
        except Exception:
            ok, reason = True, "sqf_missing"

        # build snapshot and publish
        snapshot = {
            "threshold_old": current_t,
            "threshold_new": new_t,
            "smoothed_sentiment": smoothed_sent,
            "risk": risk_val,
            "risk_mode": risk_mode,
            "sqf_ok": ok,
            "sqf_reason": reason
        }
        try:
            publish_cycle(snapshot)
        except Exception:
            import logging
            logging.getLogger("void_beast").exception("void_beast: publish_cycle failed")
    except Exception:
        import logging
        logging.getLogger("void_beast").exception("void_beast: unexpected error in __void_beast_cycle")
# ==== END VOID BEAST AUTO CYCLE HOOK ====
'''

# --- find safe insertion index after shebang, encoding, docstring, __future__ imports ---
insert_idx = 0
if lines and lines[0].startswith("#!"):
    insert_idx = 1

# skip encoding comments
enc_re = re.compile(r'\s*#.*coding[:=]\s*[-\w.]+')
while insert_idx < len(lines) and enc_re.match(lines[insert_idx]):
    insert_idx += 1

# skip module docstring
def skip_docstring(lines, idx):
    if idx >= len(lines):
        return idx
    s = lines[idx].lstrip()
    if s.startswith('"""') or s.startswith("'''"):
        quote = s[:3]
        if s.count(quote) >= 2:
            return idx + 1
        i = idx + 1
        while i < len(lines):
            if quote in lines[i]:
                return i + 1
            i += 1
        return i
    return idx

insert_idx = skip_docstring(lines, insert_idx)

# skip future imports
future_re = re.compile(r'\s*from\s+__future__\s+import')
while insert_idx < len(lines) and future_re.match(lines[insert_idx]):
    insert_idx += 1

# Now check if the integration block already exists
full_text = ''.join(lines)
if "VOID BEAST AUTO-WIRE IMPORTS" not in full_text:
    lines.insert(insert_idx, integration_block + "\n")
    lines.insert(insert_idx + 1, hook_function + "\n")
    new_text = ''.join(lines)
else:
    print("Auto-wire imports already present; will not re-insert imports/hook.")
    new_text = ''.join(lines)

# --- find first main loop (simple heuristics) ---
# look for common "while True:" patterns
loop_pattern = re.compile(r'^[ \t]*(while\s+(True|1)\s*:|while\s+not\s+\w+\s*:|while\s+\w+\s*:)', re.MULTILINE)
m = loop_pattern.search(new_text)
if m:
    # find line end of match to insert call after the 'while...' line
    start = m.start()
    # find end of that line
    line_end = new_text.find('\n', start)
    if line_end == -1:
        line_end = len(new_text)-1
    # compute indentation for insertion (same indent + 4 spaces)
    # get the matched line content and its indentation
    matched_line = new_text[start:line_end+1]
    indent_match = re.match(r'(\s*)', matched_line)
    indent = indent_match.group(1) + "    "  # insert one indent level inside loop
    hook_call = f"{indent}try:\n{indent}    __void_beast_cycle()\n{indent}except Exception as _vb_hook_e:\n{indent}    import logging\n{indent}    logging.getLogger('void_beast').exception('void_beast hook failed: %s', _vb_hook_e)\n"
    # insert hook call after the while line
    new_text = new_text[:line_end+1] + hook_call + new_text[line_end+1:]
    print("Inserted __void_beast_cycle() into first detected main loop.")
else:
    # fallback: look for "__main__" guard and insert call at its start (best-effort)
    main_guard_re = re.compile(r'if\s+__name__\s*==\s*[\'"]__main__[\'"]\s*:\s*', re.MULTILINE)
    m2 = main_guard_re.search(new_text)
    if m2:
        # find block start
        start = m2.end()
        # compute indent of the following line
        # find next line start
        next_nl = new_text.find('\n', start)
        # insert after the guard line with indentation
        indent = "    "
        hook_call = f"\n{indent}try:\n{indent}    __void_beast_cycle()\n{indent}except Exception as _vb_hook_e:\n{indent}    import logging\n{indent}    logging.getLogger('void_beast').exception('void_beast hook failed: %s', _vb_hook_e)\n"
        new_text = new_text[:start] + hook_call + new_text[start:]
        print("Inserted __void_beast_cycle() into __main__ guard (fallback).")
    else:
        print("Could not find a suitable main loop or __main__ guard to call the hook. No loop insertion was done.")
        # write file with imports and hook only (so user can call it manually or we can retry)
        # new_text already contains imports + hook; continue

# --- write modified file back ---
SRC.write_text(new_text, encoding="utf-8")
print("Wrote modified voidx2_0.py (with auto-wire). Backup:", backup.name)

# syntax check
try:
    py_compile.compile(str(SRC), doraise=True)
    print("Syntax OK for modified voidx2_0.py")
    print("Auto-wire complete. Run your bot as usual: python voidx2_0.py")
    print("If anything looks wrong restore the backup with:")
    print(f"    copy {backup.name} voidx2_0.py   (Windows CMD)")
    print(f"or    cp {backup.name} voidx2_0.py     (Unix)")
except py_compile.PyCompileError as e:
    print("Syntax ERROR after auto-wire:", e)
    print("Restoring backup to undo changes.")
    shutil.copy2(backup, SRC)
    print("Backup restored. Please paste the exact error output here and I'll fix it.")
    sys.exit(3)
