#!/usr/bin/env python3
# auto_wire_void_beast_safe.py
# Robust auto-wire that inserts the VOID BEAST imports + cycle hook safely,
# placing the imports AFTER any from __future__ imports (anywhere in file).
# Creates backup and restores on syntax errors.

import re, sys, shutil, time
from pathlib import Path
import py_compile

ROOT = Path.cwd()
SRC = ROOT / "voidx2_0_final_beast.py"

if not SRC.exists():
    print("Error: voidx2_0.py not found in", ROOT)
    sys.exit(1)

backup = ROOT / f"voidx2_0_autowire_backup_{int(time.time())}.py"
shutil.copy2(SRC, backup)
print("Backup created:", backup.name)

orig_text = SRC.read_text(encoding="utf-8")
lines = orig_text.splitlines(keepends=True)

# Defensive: if already auto-wired, abort to avoid double insertions
if "VOID BEAST AUTO-WIRE IMPORTS" in orig_text or "VOID BEAST AUTO CYCLE HOOK" in orig_text:
    print("Auto-wire markers already present in file; aborting to avoid double-insert.")
    sys.exit(0)

# Integration import block (defensive)
integration_block = r'''
# ==== VOID BEAST AUTO-WIRE IMPORTS ====
# auto-generated by auto_wire_void_beast_safe.py
try:
    import beast_helpers as vb_helpers
    import beast_threshold as vb_threshold
    import beast_risk as vb_risk
    import beast_protection as vb_protect
    import beast_dashboard as vb_dashboard
    import beast_sentiment as vb_sent
    import beast_scoring as vb_scoring
    import beast_calendar as vb_calendar
    import beast_symbols as vb_symbols
    import beast_liquidity as vb_liq
except Exception as _vb_e:
    import logging
    logging.getLogger("void_beast").warning("void_beast auto-wire import failure: %s", _vb_e)
# ==== END VOID BEAST AUTO-WIRE IMPORTS ====
'''.lstrip()

# Hook function (defensive)
hook_function = r'''
# ==== VOID BEAST AUTO CYCLE HOOK ====
def __void_beast_cycle():
    try:
        try:
            from beast_threshold import get_current_threshold, apply_gravity_and_volatility
            from beast_sentiment import SentimentEngine
            from beast_risk import compute_dynamic_risk
            from beast_dashboard import publish_cycle
            from beast_protection import sqf_check
        except Exception as _e:
            import logging
            logging.getLogger("void_beast").debug("void_beast hook: modules missing: %s", _e)
            return

        # threshold
        try:
            current_t = get_current_threshold()
        except Exception:
            current_t = 0.18

        # get cached headlines if available in globals
        try:
            g = globals()
            articles = g.get("BEAST_NEWS_CACHE") or g.get("news_cache") or []
        except Exception:
            articles = []

        # sentiment engine singleton on function object
        sent_engine = getattr(__void_beast_cycle, "_sent_engine", None)
        if sent_engine is None:
            sent_engine = SentimentEngine(alpha=0.2, window=5)
            setattr(__void_beast_cycle, "_sent_engine", sent_engine)

        try:
            smoothed_sent = sent_engine.score_from_headlines(articles or [])
        except Exception:
            smoothed_sent = 0.0

        # compute dynamic risk
        try:
            tech = globals().get("LAST_TECH_SCORE", 0.0)
            model = globals().get("LAST_MODEL_SCORE", 0.0)
            fund = globals().get("LAST_FUND_SCORE", 0.0)
            risk_val, risk_mode = compute_dynamic_risk(tech, fund, smoothed_sent)
        except Exception:
            risk_val, risk_mode = 0.003, "default"

        # apply gravity update (no volatility adjustment here)
        try:
            new_t = apply_gravity_and_volatility(current_t, volatility_adj=0.0)
        except Exception:
            new_t = current_t

        # quick SQF check best-effort
        try:
            spread_points = globals().get("CURRENT_SPREAD_POINTS", None)
            atr_now = globals().get("CURRENT_ATR", None)
            atr_avg = globals().get("ATR_AVG", None)
            recent_move_pct = globals().get("RECENT_MOVE_PCT", None)
            ok, reason = sqf_check("GENERIC", spread_points, atr_now, atr_avg, recent_move_pct)
        except Exception:
            ok, reason = True, "sqf_missing"

        snapshot = {
            "threshold_old": current_t,
            "threshold_new": new_t,
            "smoothed_sentiment": smoothed_sent,
            "risk": risk_val,
            "risk_mode": risk_mode,
            "sqf_ok": ok,
            "sqf_reason": reason
        }
        try:
            publish_cycle(snapshot)
        except Exception:
            import logging
            logging.getLogger("void_beast").exception("void_beast: publish_cycle failed")
    except Exception:
        import logging
        logging.getLogger("void_beast").exception("void_beast: unexpected error in __void_beast_cycle")
# ==== END VOID BEAST AUTO CYCLE HOOK ====
'''.lstrip()

# Find insertion index:
# Strategy: find last occurrence of any "from __future__ import" across entire file.
last_future_idx = -1
for idx, ln in enumerate(lines):
    if re.match(r'\s*from\s+__future__\s+import\b', ln):
        last_future_idx = idx

# Start insertion after:
insert_idx = 0
# preserve shebang if present
if lines and lines[0].startswith("#!"):
    insert_idx = 1

# skip encoding comment(s)
enc_re = re.compile(r'\s*#.*coding[:=]\s*[-\w.]+')
while insert_idx < len(lines) and enc_re.match(lines[insert_idx]):
    insert_idx += 1

# skip module docstring if present
def skip_doc(lines, i):
    if i >= len(lines):
        return i
    s = lines[i].lstrip()
    if s.startswith('"""') or s.startswith("'''"):
        quote = s[:3]
        if s.count(quote) >= 2:
            return i+1
        j = i+1
        while j < len(lines):
            if quote in lines[j]:
                return j+1
            j += 1
        return j
    return i

insert_idx = skip_doc(lines, insert_idx)

# If any future import found, set insertion point after the last future import line
if last_future_idx >= 0:
    insert_idx = last_future_idx + 1

# Ensure we don't insert in the middle of an indented block at insert_idx:
# move insert_idx back to previous newline (we operate on line boundaries so it's safe)

# Build new content: insert integration block + hook_function at insert_idx
new_lines = list(lines)  # copy
new_lines.insert(insert_idx, integration_block + "\n")
new_lines.insert(insert_idx + 1, hook_function + "\n")

new_text = "".join(new_lines)

# Now find suitable main loop to call the hook
# Prefer 'while True:' loops, else __main__ guard fallback
loop_match = re.search(r'^[ \t]*(while\s+(True|1)\s*:)', new_text, flags=re.MULTILINE)
if loop_match:
    mstart = loop_match.start()
    # find end of line
    line_end = new_text.find('\n', mstart)
    if line_end == -1:
        line_end = mstart
    # compute indentation
    matched_line = new_text[mstart:line_end+1]
    indent = re.match(r'(\s*)', matched_line).group(1) + "    "
    hook_call = (f"{indent}try:\n"
                 f"{indent}    __void_beast_cycle()\n"
                 f"{indent}except Exception as _vb_hook_e:\n"
                 f"{indent}    import logging\n"
                 f"{indent}    logging.getLogger('void_beast').exception('void_beast hook failed: %s', _vb_hook_e)\n")
    new_text = new_text[:line_end+1] + hook_call + new_text[line_end+1:]
    inserted_call = True
    print("Inserted __void_beast_cycle() into first detected while-loop.")
else:
    # fallback to __main__ guard
    main_match = re.search(r'if\s+__name__\s*==\s*[\'"]__main__[\'"]\s*:', new_text)
    if main_match:
        pos = main_match.end()
        indent = "    "
        hook_call = ("\n" + indent + "try:\n"
                     + indent + "    __void_beast_cycle()\n"
                     + indent + "except Exception as _vb_hook_e:\n"
                     + indent + "    import logging\n"
                     + indent + "    logging.getLogger('void_beast').exception('void_beast hook failed: %s', _vb_hook_e)\n")
        new_text = new_text[:pos] + hook_call + new_text[pos:]
        inserted_call = True
        print("Inserted __void_beast_cycle() into __main__ guard (fallback).")
    else:
        inserted_call = False
        print("Could not find loop or __main__ guard to auto-insert hook call. Integration imports and hook function were inserted; you can call __void_beast_cycle() manually or ask me to retry.")

# Write new file back
SRC.write_text(new_text, encoding="utf-8")
print("Wrote modified voidx2_0.py (with auto-wire). Backup:", backup.name)

# Syntax check
try:
    py_compile.compile(str(SRC), doraise=True)
    print("Syntax OK for modified voidx2_0.py")
    print("Auto-wire complete. Run your bot as usual: python voidx2_0.py")
    print("If anything looks wrong restore the backup with:")
    print(f"    copy {backup.name} voidx2_0.py   (Windows CMD)")
    print(f"or    cp {backup.name} voidx2_0.py     (Unix)")
except py_compile.PyCompileError as e:
    print("Syntax ERROR after auto-wire:", e)
    print("Restoring backup to undo changes.")
    shutil.copy2(backup, SRC)
    print("Backup restored. Please paste the exact error output here and I'll fix it.")
    sys.exit(3)
