#!/usr/bin/env python3 """ Robust, defensive runner for 30-day backtests.

This script is a careful drop-in replacement for the one in your repo. It:

Loads your bot module dynamically Tries multiple run_backtest signatures safely Normalizes returned data shapes into a stable CSV row format Repairs / reinits a corrupted master CSV header if necessary Writes a per-symbol log under /tmp/backtest_results 

Usage: python run_30d_backtests.py python run_30d_backtests.py BTCUSD EURUSD

This file is intended to be syntactically clean and defensive. """

import os import sys import csv import traceback import importlib.util from datetime import datetime from typing import Any

---------- Configuration ---------- 

BOT_FILENAME = "KYOTO_INFERNO_V16_fixed-5_upgraded.py" # adjust if needed REPORT_PATH = "KYOTO_V16_BACKTEST_REPORT.csv" BACKTEST_DIR = os.path.join(os.sep, "tmp", "backtest_results") DEFAULT_SYMBOLS = ["BTCUSD", "EURUSD", "USDJPY", "XAUUSD", "USOIL", "DXY"] DAYS = 30 REPORT_HEADER = ["time", "type", "entry", "exit", "pnl", "exit_time", "atr_at_entry"]

----------------------------------- 

def safe_mkdir(path: str) -> None: try: os.makedirs(path, exist_ok=True) except Exception: pass

def ensure_report_header(path: str = REPORT_PATH, header=REPORT_HEADER) -> None: """Ensure a well-formed CSV header exists. If the file is missing or corrupted, back it up and rewrite a clean header.""" try: # if file missing -> create if not os.path.exists(path): with open(path, "w", newline="", encoding="utf-8") as f: csv.writer(f).writerow(header) return

# read first line with open(path, "r", encoding="utf-8") as f: first = f.readline().strip() expected = ",".join(header) # compare ignoring whitespace differences if not first or first.replace(" ", "") != expected.replace(" ", ""): # backup old file try: stamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ") backup = f"{path}.bak.{stamp}" os.replace(path, backup) print(f"Backed up existing report to {backup}") except Exception: # if rename fails, try to continue and overwrite pass with open(path, "w", newline="", encoding="utf-8") as f: csv.writer(f).writerow(header) except Exception as e: print("ensure_report_header failed:", e) 

def load_bot_module(bot_filename: str): """Dynamically import the bot module by path. Returns module object.""" if not os.path.exists(bot_filename): raise FileNotFoundError(f"Bot file not found: {bot_filename}") spec = importlib.util.spec_from_file_location("kyoto_bot", bot_filename) bot = importlib.util.module_from_spec(spec) spec.loader.exec_module(bot) return bot

def _coerce_to_list(value: Any): """Safely coerce returned value into a list of trade-like rows. Keeps defensive checks so weird returns (int, None, scalar) don't break us.""" if value is None: return [] if isinstance(value, list): return value if isinstance(value, dict): # prefer trades_list, trades keys t = value.get("trades_list") or value.get("trades") if isinstance(t, list): return t # maybe single-trade encoded in top-level dict if all(k in value for k in ("entry", "exit", "pnl")): return [value] return [] # anything else (int, float, str) -> no trades return []

def normalize_and_append_rows(report_path: str, trades_list, start_ts: str): """Append normalized rows to report_path. Guarantees columns match REPORT_HEADER. trades_list can be list of dicts or sequences. Defensive against garbage.""" try: with open(report_path, "a", newline="", encoding="utf-8") as rf: writer = csv.writer(rf) for row in trades_list: try: if isinstance(row, dict): time_v = row.get("time", start_ts) type_v = row.get("type", "") entry_v = row.get("entry", 0) exit_v = row.get("exit", 0) pnl_v = row.get("pnl", 0) exit_time_v = row.get("exit_time", "") atr_v = row.get("atr_at_entry", row.get("atr", 0)) writer.writerow([time_v, type_v, entry_v, exit_v, pnl_v, exit_time_v, atr_v]) else: # sequence-like: try to convert to list and pad/trim seq = list(row) # ensure at least 7 entries seq = (seq + [""] * 7)[:7] writer.writerow(seq) except Exception: # in-case one row is malformed, write a sentinel writer.writerow([start_ts, "error", 0, 0, 0, "", 0]) except Exception as e: print("Failed to append rows to report:", e)

def try_run_backtest(bot, v15, sym: str): """Try common run_backtest signatures and return raw result or raise the last exception.""" last_exc = None if not hasattr(bot, "run_backtest"): raise AttributeError("Bot module has no run_backtest function") # try progressive signatures try: return bot.run_backtest(v15, symbol=sym, days=DAYS) except TypeError as e: last_exc = e try: return bot.run_backtest(symbol=sym, days=DAYS) except TypeError as e: last_exc = e try: return bot.run_backtest(sym, DAYS) except Exception as e: last_exc = e # none worked raise last_exc or RuntimeError("run_backtest attempts failed")

def main(argv): print("Starting safe 30-day backtests runner...") symbols = argv[1:] if len(argv) > 1 else DEFAULT_SYMBOLS

safe_mkdir(BACKTEST_DIR) ensure_report_header(REPORT_PATH, REPORT_HEADER) # load bot module try: bot = load_bot_module(BOT_FILENAME) print(f"Loaded bot module from {BOT_FILENAME}") except Exception as e: print("Failed to load bot module:", e) traceback.print_exc() return 2 # try to obtain v15 adapter if the bot exposes a loader v15 = None try: if hasattr(bot, "load_v15_module") and callable(bot.load_v15_module): try: v15 = bot.load_v15_module() print("v15 loaded:", getattr(v15, "__name__", v15)) except Exception: # some loaders accept no args or are named differently try: v15 = bot.load_v15_module(None) print("v15 loaded (with arg):", getattr(v15, "__name__", v15)) except Exception: v15 = None else: loader = getattr(bot, "load_v15", None) or getattr(bot, "load_v15_impl", None) if callable(loader): try: v15 = loader() print("v15 loaded (via alt loader):", getattr(v15, "__name__", v15)) except Exception: v15 = None else: print("No v15 loader found in bot module; continuing with v15=None") except Exception as e: print("Exception while loading v15:", e) v15 = None for sym in symbols: log_path = os.path.join(BACKTEST_DIR, f"backtest_{sym}_30d.log") try: print(f"--- backtest start: {sym}") start_ts = datetime.utcnow().isoformat() try: ret = try_run_backtest(bot, v15, sym) except Exception as e_run: tb = traceback.format_exc() with open(log_path, "w", encoding="utf-8") as lf: lf.write(f"Exception running run_backtest for {sym}:\n") lf.write(tb) print(f"Backtest for {sym} raised exception. See {log_path}") # append placeholder to master CSV so analyzers don't fail normalize_and_append_rows(REPORT_PATH, [{"time": start_ts, "type": "error", "entry": 0, "exit": 0, "pnl": 0, "exit_time": "", "atr_at_entry": 0}], start_ts) continue # persist raw return to per-symbol log for debugging try: with open(log_path, "w", encoding="utf-8") as lf: lf.write(f"Backtest returned (repr): {repr(ret)}\n") except Exception: pass trades_list = _coerce_to_list(ret) # If single dict returns were provided (single trade), coerce if not trades_list and isinstance(ret, dict) and all(k in ret for k in ("entry", "exit", "pnl")): trades_list = [ret] if trades_list: normalize_and_append_rows(REPORT_PATH, trades_list, start_ts) else: # no trades recorded, append a 'none' placeholder row for observability normalize_and_append_rows(REPORT_PATH, [{"time": start_ts, "type": "none", "entry": 0, "exit": 0, "pnl": 0, "exit_time": "", "atr_at_entry": 0}], start_ts) print(f"Saved {log_path}") except Exception as outer: tb = traceback.format_exc() print(f"Outer exception for {sym}: {outer}") try: with open(log_path, "a", encoding="utf-8") as lf: lf.write("Outer exception:\n") lf.write(tb) except Exception: pass print("All backtests finished. Check", BACKTEST_DIR) return 0 

if name == "main": sys.exit(main(sys.argv))

